version: 2.1
orbs:
  node: circleci/node@5.0.1
  heroku: circleci/heroku@1.2.6

jobs:
  say-hello:
    docker:
      - image: cimg/node:17.7.2
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - main